@session = connect.sid=s%3AZj55QxC0bqcLoNCCo7s3NgxTWU9xEBBc.jL2ZD3VWBtb3UmUPg%2BQQE%2BL6%2Fyq%2B685kHPwg0SDsDls;
###
GET http://localhost:3001/api/front/pages HTTP/1.1
###
GET http://localhost:3001/api/front/content/1 HTTP/1.1
###
GET http://localhost:3001/api/pages HTTP/1.1
Cookie: connect.sid = {{session}}
###
POST http://localhost:3001/api/sessions HTTP/1.1
Content-Type: application/json

{
    "username"  : "mario.rossi@polito.it",
    "password" : "password"
}
###
GET http://localhost:3001/api/front/content/1 HTTP/1.1
###