@session = s%3AjfRQytjDeyvRAUfY5OpLwHRrO7vOu7fW.RWhrxRKRZ%2F8Duozk%2BenoZQgUdUWhx1DkjcsrtrM8Yg0;
@component1 = {page : 1,'type' : 'header','content' : 'Header pagina 1','position' : 0}
###
GET http://localhost:3001/api/front/pages HTTP/1.1
###
GET http://localhost:3001/api/front/pages/4 HTTP/1.1
###
GET http://localhost:3001/api/pages HTTP/1.1
Cookie: connect.sid = {{session}}
###
POST http://localhost:3001/api/sessions HTTP/1.1
Content-Type: application/json

{
    "username"  : "mario.rossi@polito.it",
    "password" : "password"
}
###
GET http://localhost:3001/api/front/pages/1 HTTP/1.1
###
PUT http://localhost:3001/api/pages/4 HTTP/1.1
Cookie: connect.sid = {{session}}
Content-Type: application/json

{
    "id" : 4,
    "title" : "Star wars : the dawn of the force",
    "author" : "Mario",
    "creationDate" : "2023-05-04",
    "publishDate" : "2023-05-24",
    "contentBlocks" : [
        {
            "page" : 4,
            "type" : "Header",
            "content" : "Star wars : the dawn of the force",
            "position" : 0
        },
        {
            "page" : 4,
            "type" : "body",
            "content" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nullam euismod, nisl eget ultricies ultricies, nunc nisl aliquam nunc, vitae ultricies ne que nunc eget nunc. Nulla facilisi. Nullam euismod, nisl eget ultricies ultricies, nunc nisl aliquam nunc, vitae ultricies ne que nunc eget nunc.",
            "position" : 1    
        },
        {
            "page" : 4,
            "type" : "Image",
            "content" : "starwars.jpeg",
            "position" : 2 
        }]
}
###
DELETE http://localhost:3001/api/pages/5 HTTP/1.1

###
PUT http://localhost:3001/api/pages/4 HTTP/1.1
Cookie: connect.sid = {{session}}
Content-Type: application/json

{
    "id" : 2,
    "title" : "Star wars : the dawn of the force",
    "author" : "John",
    "creationDate" : "2023-05-04",
    "publishDate" : "2023-05-24",
    "contentBlocks" : [
        {
            "page" : 4,
            "type" : "Header",
            "content" : "Star wars : the dawn of the force",
            "position" : 0
        },
        {
            "page" : 4,
            "type" : "body",
            "content" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nullam euismod, nisl eget ultricies ultricies, nunc nisl aliquam nunc, vitae ultricies ne que nunc eget nunc. Nulla facilisi. Nullam euismod, nisl eget ultricies ultricies, nunc nisl aliquam nunc, vitae ultricies ne que nunc eget nunc.",
            "position" : 1    
        },
        {
            "page" : 4,
            "type" : "Image",
            "content" : "starwars.jpeg",
            "position" : 2 
        }]
}
###